document.write('<script type="text/javascript" src="Cesium/Cesium.js" ></script>')
document.write('<link rel="stylesheet" type="text/css" href="Cesium/Widgets/widgets.css" />')
document.write('<script type="text/javascript" src="Cesium/plugin/Navigation/viewerCesiumNavigationMixin.js" ></script>')
document.write('<script type="text/javascript" src="Cesium/plugin/TMSImageProvider/TMSImageProvider.js" ></script>')
document.write('<script type="text/javascript" src="Cesium/plugin/dis.js" ></script>')
document.write('<script type="text/javascript" src="Cesium/plugin/jquery-3.1.1.min.js" ></script>')
document.write('<script type="text/javascript" src="Cesium/plugin/html2canvas.svg.js" ></script>')
document.write('<script type="text/javascript" src="Cesium/plugin/html2canvas.js" ></script>')
document.write('<link rel="stylesheet" type="text/css" href="CesiumSDK.css" />')
document.write('<script type="text/javascript" src="CesiumSDK.js" ></script>')
document.write('<script type="text/javascript" src="handler.js" ></script>')
document.write('<script type="text/javascript" src="dis.js" ></script>')
